% This script loads in the data files generated by a GA run

% Count files
fnum  = 1;
while exist(['GAdata_gen',num2str(fnum),'.mat'],'file'), fnum=fnum+1; end
fnum = fnum - 1;


% Read them
for i=1:fnum
    load(['GAdata_gen',num2str(i),'.mat'])
    disp(['Generation ',num2str(gen)])
    disp(['Best objective value: ',num2str(bestobj)])
    disp('The best design: ')
    bestvar(:)
    
    % Insert data analysis here
    % Data available in each file
    %
    % POP - population (cell array, in binary)
    % POPDecoded - population (cell array, real valued variables)
    % POPfit - vector of fitness values
    % bestobj, bestvar - the best of generation gen after eval_count
    % evaluations
    % ev_hist, history - evaluations - objective history     
    
    
    
    % end of data analysis
end

plot((0:length(history)-1),history)
xlabel('Generations'); ylabel('Objective value');
title('Objective function history')

